package zw.co.tinysolutions.model.ext;
// Generated Sep 2, 2017 2:22:32 PM by Hibernate Tools 4.3.1

import java.util.logging.Logger;

/**
 * SmtpConfiguration generated by hbm2java
 */
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
@JsonIgnoreProperties(ignoreUnknown = true)
public class SmtpConfiguration implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    private static final Logger LOG = Logger.getLogger(SmtpConfiguration.class.getName());
    private Integer id;
    private String smtpParameter;
    private String smtpValue;
    private boolean status;
    private SysConnectedSystems sysConnectedSystems;

    public SmtpConfiguration() {
    }

    public SmtpConfiguration(Integer id, String smtpParameter, String smtpValue, boolean status, SysConnectedSystems sysConnectedSystems) {
        this.id = id;
        this.smtpParameter = smtpParameter;
        this.smtpValue = smtpValue;
        this.status = status;
        this.sysConnectedSystems = sysConnectedSystems;
    }

    
public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

 public String getSmtpParameter() {
        return this.smtpParameter;
    }

    public void setSmtpParameter(String smtpParameter) {
        this.smtpParameter = smtpParameter;
    }

   public String getSmtpValue() {
        return this.smtpValue;
    }

    public void setSmtpValue(String smtpValue) {
        this.smtpValue = smtpValue;
    }

  public boolean isStatus() {
        return this.status;
    }

    public void setStatus(boolean status) {
        this.status = status;
    }

  /**
     * @return the sysConnectedSystems
     */
   public SysConnectedSystems getSysConnectedSystems() {
        return sysConnectedSystems;
    }

    /**
     * @param sysConnectedSystems the sysConnectedSystems to set
     */
    public void setSysConnectedSystems(SysConnectedSystems sysConnectedSystems) {
        this.sysConnectedSystems = sysConnectedSystems;
    }

    
    
}
