package zw.co.tinysolutions.model.ext;
// Generated Sep 2, 2017 2:22:32 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import java.util.logging.Logger;

/**
 * SysContactInformationTypes generated by hbm2java
 */
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
@JsonIgnoreProperties(ignoreUnknown = true)
public class SysContactInformationTypes implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    private static final Logger LOG = Logger.getLogger(SysContactInformationTypes.class.getName());
    private Integer id;
    private String contactType;
    private String typeDescription;
    private boolean status;
    private Set<SysSystemUsersContactInformation> sysSystemUsersContactInformations = new HashSet<>(0);

    public SysContactInformationTypes() {
    }

    public SysContactInformationTypes(boolean status) {
        this.status = status;
    }

    public SysContactInformationTypes(Integer id, String contactType, String typeDescription, boolean status) {
        this.id = id;
        this.contactType = contactType;
        this.typeDescription = typeDescription;
        this.status = status;
    }

 
   public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

  public String getContactType() {
        return this.contactType;
    }

    public void setContactType(String contactType) {
        this.contactType = contactType;
    }

   public String getTypeDescription() {
        return this.typeDescription;
    }

    public void setTypeDescription(String typeDescription) {
        this.typeDescription = typeDescription;
    }

  public boolean isStatus() {
        return this.status;
    }

    public void setStatus(boolean status) {
        this.status = status;
    }

   public Set<SysSystemUsersContactInformation> getSysSystemUsersContactInformations() {
        return this.sysSystemUsersContactInformations;
    }

    public void setSysSystemUsersContactInformations(Set<SysSystemUsersContactInformation> sysSystemUsersContactInformations) {
        this.sysSystemUsersContactInformations = sysSystemUsersContactInformations;
    }

    
}
