package zw.co.tinysolutions.model.ext;
// Generated Sep 2, 2017 2:22:32 PM by Hibernate Tools 4.3.1

import java.util.logging.Logger;

/**
 * SysMaritalStatus generated by hbm2java
 */
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
@JsonIgnoreProperties(ignoreUnknown = true)
public class SysMaritalStatus implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    private static final Logger LOG = Logger.getLogger(SysMaritalStatus.class.getName());
    private Integer id;
    private String maritalStatus;
    private boolean status;

    public SysMaritalStatus() {
    }

    public SysMaritalStatus(Integer id, String maritalStatus, boolean status) {
        this.id = id;
        this.maritalStatus = maritalStatus;
        this.status = status;
    } 
 
public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

   public String getMaritalStatus() {
        return this.maritalStatus;
    }

    public void setMaritalStatus(String maritalStatus) {
        this.maritalStatus = maritalStatus;
    }

   public boolean isStatus() {
        return this.status;
    }

    public void setStatus(boolean status) {
        this.status = status;
    }

}
