package zw.co.tinysolutions.model.ext;
// Generated Sep 2, 2017 2:22:32 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.logging.Logger;

/**
 * SysUserPasswords generated by hbm2java
 */
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
@JsonIgnoreProperties(ignoreUnknown = true)
public class SysUserPasswords implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    private static final Logger LOG = Logger.getLogger(SysUserPasswords.class.getName());

    private Integer id;
    private SysSystemUsers sysSystemUsers;
    private String password;
    private Date passwordDate;
    private boolean status;

    public SysUserPasswords() {
    }

    public SysUserPasswords(boolean status) {
        this.status = status;
    }

    public SysUserPasswords(SysSystemUsers sysSystemUsers, String password, Date passwordDate, boolean status) {
        this.sysSystemUsers = sysSystemUsers;
        this.password = password;
        this.passwordDate = passwordDate;
        this.status = status;
    }

  public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

  public SysSystemUsers getSysSystemUsers() {
        return this.sysSystemUsers;
    }

    public void setSysSystemUsers(SysSystemUsers sysSystemUsers) {
        this.sysSystemUsers = sysSystemUsers;
    }

   public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public Date getPasswordDate() {
        return this.passwordDate;
    }

    public void setPasswordDate(Date passwordDate) {
        this.passwordDate = passwordDate;
    }

  public boolean isStatus() {
        return this.status;
    }

    public void setStatus(boolean status) {
        this.status = status;
    }

}
